In [10]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [11]:
df = pd.read_csv("../data/googleplaystore_features.csv")

df.head()

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,App_Age,Review_Ratio,Log_Reviews,Log_Installs,Paid_App
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159.0,19.0,10000.0,Free,0.0,Everyone,Art & Design,2018-01-07,213,0.015900,5.075174,9.210440,0
1,Coloring book moana,ART_AND_DESIGN,3.9,967.0,14.0,500000.0,Free,0.0,Everyone,Art & Design;Pretend Play,2018-01-15,205,0.001934,6.875232,13.122365,0
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510.0,8.7,5000000.0,Free,0.0,Everyone,Art & Design,2018-08-01,7,0.017502,11.379520,15.424949,0
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644.0,25.0,50000000.0,Free,0.0,Teen,Art & Design,2018-06-08,61,0.004313,12.281389,17.727534,0
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967.0,2.8,100000.0,Free,0.0,Everyone,Art & Design;Creativity,2018-06-20,49,0.009670,6.875232,11.512935,0

In [12]:
df = pd.read_csv("../data/merged_dataset.csv")

In [24]:
X = df[
[
"Reviews",
"Installs",
"Size",
"Price",
"App_Age",
"Review_Ratio",
"Log_Reviews",
"Log_Installs",
"Paid_App",
"Sentiment_Polarity",
"Sentiment_Subjectivity"
]
]

y = df["Rating"]

In [67]:
from sklearn.preprocessing import LabelEncoder

le_category = LabelEncoder()
le_content = LabelEncoder()
le_genres = LabelEncoder()

df["Category"] = le_category.fit_transform(df["Category"])
df["Content Rating"] = le_content.fit_transform(df["Content Rating"])
df["Genres"] = le_genres.fit_transform(df["Genres"])

In [68]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [69]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [70]:
X.isnull().sum()

Reviews                   0
Installs                  0
Size                      0
Price                     0
App_Age                   0
Review_Ratio              0
Log_Reviews               0
Log_Installs              0
Paid_App                  0
Sentiment_Polarity        0
Sentiment_Subjectivity    0
dtype: int64

In [71]:
df["Review_Ratio"] = df["Review_Ratio"].replace([np.inf, -np.inf], np.nan)
df["Review_Ratio"] = df["Review_Ratio"].fillna(0)

In [72]:
X = df[
[
"Reviews",
"Installs",
"Size",
"Price",
"App_Age",
"Review_Ratio",
"Log_Reviews",
"Log_Installs",
"Paid_App",
"Sentiment_Polarity",
"Sentiment_Subjectivity"
]
]

In [73]:
print(X.isnull().sum())

Reviews                   0
Installs                  0
Size                      0
Price                     0
App_Age                   0
Review_Ratio              0
Log_Reviews               0
Log_Installs              0
Paid_App                  0
Sentiment_Polarity        0
Sentiment_Subjectivity    0
dtype: int64

In [74]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

### LinearRegression

In [75]:
lr = LinearRegression()

lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

In [76]:
print("Linear Regression")
print("MAE :", mean_absolute_error(y_test, lr_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, lr_pred)))
print("R2  :", r2_score(y_test, lr_pred))

Linear Regression
MAE : 0.30134239884065456
RMSE: 0.44762384805242583
R2  : 0.1272768817680614

### Decision Tree

In [77]:
dt = DecisionTreeRegressor(random_state=42)

dt.fit(X_train, y_train)

dt_pred = dt.predict(X_test)

In [78]:
print("Decision Tree")
print("MAE :", mean_absolute_error(y_test, dt_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, dt_pred)))
print("R2  :", r2_score(y_test, dt_pred))

Decision Tree
MAE : 0.3982142857142859
RMSE: 0.6292461936323271
R2  : -0.7246113581743625

### Random forest

In [79]:
rf = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

In [80]:
print("Random Forest")
print("MAE :", mean_absolute_error(y_test, rf_pred))
print("RMSE:", np.sqrt(mean_squared_error(y_test, rf_pred)))
print("R2  :", r2_score(y_test, rf_pred))

Random Forest
MAE : 0.2952899613899614
RMSE: 0.4585590985315224
R2  : 0.08411556676205123

### Compare Models

In [81]:
results = pd.DataFrame({
    "Model": [
        "Linear Regression",
        "Decision Tree",
        "Random Forest"
    ],
    "MAE": [
        mean_absolute_error(y_test, lr_pred),
        mean_absolute_error(y_test, dt_pred),
        mean_absolute_error(y_test, rf_pred)
    ],
    "RMSE": [
        np.sqrt(mean_squared_error(y_test, lr_pred)),
        np.sqrt(mean_squared_error(y_test, dt_pred)),
        np.sqrt(mean_squared_error(y_test, rf_pred))
    ],
    "R2 Score": [
        r2_score(y_test, lr_pred),
        r2_score(y_test, dt_pred),
        r2_score(y_test, rf_pred)
    ]
})

results

               Model       MAE      RMSE  R2 Score
0  Linear Regression  0.301342  0.447624  0.127277
1      Decision Tree  0.398214  0.629246 -0.724611
2      Random Forest  0.295290  0.458559  0.084116

In [82]:
best_model = rf

print("Best Model: Random Forest")

Best Model: Random Forest

In [90]:
import joblib
joblib.dump(best_model, "../model.pkl")

['../model.pkl']

In [84]:
print(type(rf))

<class 'sklearn.ensemble._forest.RandomForestRegressor'>

In [86]:
print(df["Category"].head())

0    0
1    0
2    0
3    0
4    0
Name: Category, dtype: int64